In [1]:
path = 'C:/Users/ariad/OneDrive/Desktop/Proyecto/DGEAnalysis/GWAS'
import pandas as pd
import numpy as np

In [3]:
score = pd.read_csv(path + "/MONDO_0002009_associations_export.tsv", sep="\t", index_col=0)

In [4]:
score

,pValue,pValueAnnotation,riskFrequency,orValue,beta,ci,mappedGenes,traitName,efoTraits,bgTraits,accessionId,locations,pubmedId,author
riskAllele,,,,,,,,,,,,,,
rs6436132-T,3.000000e-09,-,NR,3.34,-,[2.2-5.07],PTPRN,Early-onset postpartum depression,postpartum depression,-,GCST90624430,2:219295922,38555957,Tebeka S
rs184644645-TTATG,9.000000e-09,-,NR,4.88,-,[2.7-8.82],RAD51B,Early-onset postpartum depression,postpartum depression,-,GCST90624430,14:68082493,38555957,Tebeka S
rs6028719-T,2.000000e-08,-,NR,1.85,-,[1.49-2.3],"RN7SL680P,HSPE1P1",Late-onset postpartum depression,postpartum depression,-,GCST90624431,20:39920405,38555957,Tebeka S
rs6028721-G,2.000000e-08,-,NR,1.85,-,[1.49-2.3],"HSPE1P1,RN7SL680P",Late-onset postpartum depression,postpartum depression,-,GCST90624431,20:39921753,38555957,Tebeka S
rs6028723-C,2.000000e-08,-,NR,1.85,-,[1.49-2.3],"RN7SL680P,HSPE1P1",Late-onset postpartum depression,postpartum depression,-,GCST90624431,20:39922976,38555957,Tebeka S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
rs4129585-?,2.000000e-15,-,NR,-,-,-,TSNARE1,"Anorexia nervosa, attention-deficit/hyperactiv...","obsessive-compulsive disorder,attention defici...",-,GCST009600,8:142231572,31835028,Cross-Disorder Group of the Psychiatric Genomi...
rs1615350-?,5.000000e-10,-,NR,-,-,-,MPHOSPH9,"Anorexia nervosa, attention-deficit/hyperactiv...","obsessive-compulsive disorder,attention defici...",-,GCST009600,12:123165788,31835028,Cross-Disorder Group of the Psychiatric Genomi...
rs4244354-?,2.000000e-09,-,NR,-,-,-,"TRIM8,ARL3","Anorexia nervosa, attention-deficit/hyperactiv...","obsessive-compulsive disorder,attention defici...",-,GCST009600,10:102666420,31835028,Cross-Disorder Group of the Psychiatric Genomi...
rs4298967-?,8.000000e-20,-,NR,-,-,-,"CACNA1C,CACNA1C-IT3","Anorexia nervosa, attention-deficit/hyperactiv...","obsessive-compulsive disorder,attention defici...",-,GCST009600,12:2299028,31835028,Cross-Disorder Group of the Psychiatric Genomi...
rs4380187-?,8.000000e-12,-,NR,-,-,-,"ZNF804A,ELF2P4","Anorexia nervosa, attention-deficit/hyperactiv...","obsessive-compulsive disorder,attention defici...",-,GCST009600,2:184947213,31835028,Cross-Disorder Group of the Psychiatric Genomi...

In [7]:
traits = ["Clinical depression",
"Lifetime major depressive disorder (AutoComplete Impute and observed)",
"Lifetime major depressive disorder (AutoComplete Impute)",
"Lifetime major depressive disorder (MTAG)",
"Lifetime major depressive disorder (SoftImpute and observed)",
"Lifetime major depressive disorder (SoftImpute)",
"Major depressive disorder",
"Major depressive disorder (broad)",
"Major depressive disorder (ICD-10 coded)",
"Major depressive disorder (lifetime)",
"Major depressive disorder (MTAG)",
"Major depressive disorder (PheCode 296.22)",
"Major depressive disorder (probable)",
"Major depressive disorder (stressful life events interaction)",
"Major depressive disorder (unexposed to adversity)"]

In [8]:
score.iloc[:,7].isin(traits)

riskAllele
rs6436132-T          False
rs184644645-TTATG    False
rs6028719-T          False
rs6028721-G          False
rs6028723-C          False
                     ...
rs4129585-?          False
rs1615350-?          False
rs4244354-?          False
rs4298967-?          False
rs4380187-?          False
Name: traitName, Length: 3989, dtype: bool

In [10]:
filtered=score[score.iloc[:,7].isin(traits)]

In [11]:
filtered

,pValue,pValueAnnotation,riskFrequency,orValue,beta,ci,mappedGenes,traitName,efoTraits,bgTraits,accessionId,locations,pubmedId,author
riskAllele,,,,,,,,,,,,,,
rs4435501-A,4.000000e-06,-,NR,-,0.13 unit increase,[0.071-0.189],SNRNP200,Major depressive disorder,major depressive disorder,-,GCST005231,2:96315631,29317602,Hall LS
rs6893200-T,5.000000e-06,(females),NR,-,0.11 unit decrease,[0.071-0.149],"CTNND2,DAP-DT",Major depressive disorder,major depressive disorder,-,GCST005231,5:10806645,29317602,Hall LS
rs111404313-A,4.000000e-06,(females),NR,-,0.32 unit decrease,[0.18-0.46],CASP8AP2,Major depressive disorder,major depressive disorder,-,GCST005231,6:89859111,29317602,Hall LS
rs9648182-A,9.000000e-08,(females),0.12,-,0.17 unit decrease,[0.11-0.23],"RBMX2P4,ETV1",Major depressive disorder,major depressive disorder,-,GCST005231,7:13755224,29317602,Hall LS
rs10227749-T,4.000000e-06,(females),NR,-,0.12 unit increase,[0.061-0.179],DGKB,Major depressive disorder,major depressive disorder,-,GCST005231,7:14404267,29317602,Hall LS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
chr11:113370758-G,1.000000e-17,-,0.6416,-,0.04049 unit increase,[0.031-0.05],-,Major depressive disorder (PheCode 296.22),major depressive disorder,-,GCST90476512,-,39024449,Verma A
chr14:42076434-C,1.000000e-14,-,0.493,-,0.03351 unit increase,[0.024-0.043],-,Major depressive disorder (PheCode 296.22),major depressive disorder,-,GCST90476512,-,39024449,Verma A
rs6877087-?,8.000000e-08,-,NR,-,-,-,"FGF18,SMIM23",Major depressive disorder (PheCode 296.22),major depressive disorder,-,GCST90651796,5:171554586,40465716,Liu TY
rs17156280-C,2.000000e-07,-,0.142,-,-,-,CACNA2D1,Major depressive disorder (stressful life even...,"self rated health,stressful life event measure...",-,GCST003319,7:82414674,26845276,Ikeda M
rs10485715-C,8.000000e-09,-,0.144,-,-,-,"LINC01428,LINC01751",Major depressive disorder (stressful life even...,"self rated health,stressful life event measure...",-,GCST003319,20:7279278,26845276,Ikeda M